import { defineArrayMember, defineField, defineType } from "sanity";
import { DocumentTextIcon, ImageIcon } from "@sanity/icons";

const paragraphs = (name = "body", title = "Body") =>
  defineField({ name, title, type: "array", of: [defineArrayMember({ type: "text", rows: 3 })] });

const anchor = defineField({ name: "id", title: "Anchor ID (optional)", type: "string" });
const image = (name = "image", title = "Image") =>
  defineField({ name, title, type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "Alternative text", type: "string", validation: (rule) => rule.required() })] });

const mediaFields = [
  defineField({ name: "mediaType", title: "Media type", type: "string", initialValue: "image", options: { layout: "radio", list: [{ title: "Image", value: "image" }, { title: "Video URL", value: "video" }, { title: "Mux video", value: "mux" }] } }),
  defineField({ name: "image", title: "Image", type: "image", options: { hotspot: true }, hidden: ({ parent }) => parent?.mediaType !== "image", fields: [defineField({ name: "alt", title: "Alternative text", type: "string", validation: (rule) => rule.required() })] }),
  defineField({ name: "video", title: "Video URL", type: "url", hidden: ({ parent }) => parent?.mediaType !== "video" }),
  defineField({ name: "muxVideo", title: "Mux video", type: "mux.video", hidden: ({ parent }) => parent?.mediaType !== "mux" }),
  defineField({ name: "alt", title: "Alternative text", type: "string" }),
  defineField({ name: "caption", title: "Caption (optional)", type: "string" }),
];

const preview = (fallback: string) => ({
  select: { title: "heading", subtitle: "eyebrow", media: "image" },
  prepare: ({ title, subtitle, media }: { title?: string; subtitle?: string; media?: unknown }) => ({ title: title || fallback, subtitle, media }),
});

export const narrative = defineType({ name: "narrative", title: "Narrative", type: "object", icon: DocumentTextIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string" }), paragraphs(), defineField({ name: "subheading", type: "string" }), defineField({ name: "largeQuestion", title: "Callout", type: "text", rows: 2 })], preview: preview("Narrative") });
export const statement = defineType({ name: "statement", title: "Statement", type: "object", icon: DocumentTextIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", title: "Statement", type: "text", rows: 3, validation: (rule) => rule.required() }), paragraphs("body", "Supporting copy")], preview: preview("Statement") });
export const designDecision = defineType({ name: "designDecision", title: "Design Decision", type: "object", icon: DocumentTextIcon, fields: [anchor, defineField({ name: "number", type: "string", title: "Number / label" }), defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string", validation: (rule) => rule.required() }), defineField({ name: "subheading", type: "string" }), paragraphs("context", "Context"), paragraphs("decision", "Decision"), paragraphs("why", "Why"), paragraphs("tradeoff", "Trade-off"), defineField({ name: "decisionPoints", title: "Decision points", type: "array", of: [defineArrayMember({ type: "object", fields: [defineField({ name: "title", type: "string", validation: (rule) => rule.required() }), defineField({ name: "body", type: "text", rows: 2 })] })] }), ...mediaFields], preview: preview("Design decision") });
export const media = defineType({ name: "media", title: "Media", type: "object", icon: ImageIcon, fields: [anchor, ...mediaFields, defineField({ name: "variant", title: "Layout", type: "string", initialValue: "wide", options: { layout: "radio", list: [{ title: "Contained", value: "contained" }, { title: "Wide", value: "wide" }, { title: "Full bleed", value: "fullBleed" }] } }), defineField({ name: "borderless", title: "Borderless", type: "boolean", initialValue: false })], preview: { select: { title: "caption", subtitle: "mediaType", media: "image" }, prepare: ({ title, subtitle, media }) => ({ title: title || "Media", subtitle, media }) } });
export const feature = defineType({ name: "feature", title: "Feature", type: "object", icon: ImageIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string" }), paragraphs(), defineField({ name: "variant", title: "Layout", type: "string", initialValue: "mediaRight", options: { layout: "radio", list: [{ title: "Media left", value: "mediaLeft" }, { title: "Media right", value: "mediaRight" }, { title: "Media top", value: "mediaTop" }, { title: "Full width", value: "fullWidth" }, { title: "Sticky", value: "sticky" }] } }), ...mediaFields], preview: preview("Feature") });
export const highlightFeature = defineType({ name: "highlightFeature", title: "Highlight Feature", type: "object", icon: ImageIcon, fields: [anchor, defineField({ name: "number", title: "Number / label", type: "string", description: "For example: 02." }), defineField({ name: "heading", title: "Heading", type: "string", validation: (rule) => rule.required() }), defineField({ name: "body", title: "Description", type: "text", rows: 3 }), ...mediaFields], preview: preview("Highlight feature") });
export const gallery = defineType({ name: "gallery", title: "Gallery", type: "object", icon: ImageIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string" }), defineField({ name: "images", title: "Screens", type: "array", of: [defineArrayMember({ type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", type: "string", title: "Alternative text", validation: (rule) => rule.required() }), defineField({ name: "caption", type: "string" })] })], validation: (rule) => rule.min(1) }), defineField({ name: "variant", title: "Layout", type: "string", initialValue: "grid", options: { layout: "radio", list: [{ title: "Grid", value: "grid" }, { title: "Wide", value: "wide" }] } })], preview: preview("Gallery") });
export const process = defineType({ name: "process", title: "Process", type: "object", icon: DocumentTextIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string" }), paragraphs(), defineField({ name: "steps", title: "Steps", type: "array", of: [defineArrayMember({ type: "object", fields: [defineField({ name: "title", type: "string", validation: (rule) => rule.required() }), defineField({ name: "body", type: "text", rows: 3 }), image()] })] })], preview: preview("Process") });
export const comparison = defineType({ name: "comparison", title: "Comparison", type: "object", icon: ImageIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string" }), paragraphs(), image("beforeImage", "Before image"), defineField({ name: "beforeLabel", type: "string" }), image("afterImage", "After image"), defineField({ name: "afterLabel", type: "string" }), defineField({ name: "variant", title: "Layout", type: "string", initialValue: "sideBySide", options: { layout: "radio", list: [{ title: "Side by side", value: "sideBySide" }, { title: "Interactive wipe", value: "slider" }] } }), defineField({ name: "caption", type: "string" })], preview: preview("Comparison") });
export const results = defineType({ name: "results", title: "Results", type: "object", icon: DocumentTextIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string" }), paragraphs(), defineField({ name: "items", title: "Outcomes", type: "array", of: [defineArrayMember({ type: "object", fields: [defineField({ name: "value", type: "string", validation: (rule) => rule.required() }), defineField({ name: "label", type: "string", validation: (rule) => rule.required() }), defineField({ name: "detail", type: "text", rows: 2 })] })] })], preview: preview("Results") });
export const reflection = defineType({ name: "reflection", title: "Reflection", type: "object", icon: DocumentTextIcon, fields: [anchor, defineField({ name: "eyebrow", type: "string" }), defineField({ name: "heading", type: "string" }), paragraphs(), defineField({ name: "items", title: "Learnings", type: "array", of: [defineArrayMember({ type: "object", fields: [defineField({ name: "number", type: "string" }), defineField({ name: "heading", type: "string", validation: (rule) => rule.required() }), defineField({ name: "body", type: "text", rows: 3 })] })] })], preview: preview("Reflection") });

export const caseStudyBlockTypes = [narrative, statement, designDecision, media, feature, highlightFeature, gallery, process, comparison, results, reflection];
